repos:
-   repo: local
    hooks:
    -   id: lint
        name: lint
        entry: docker compose run --rm --no-TTY bot bash ops/lint.sh
        language: system
        verbose: true
        pass_filenames: false
-   repo: local
    hooks:
    -   id: test
        name: test
        entry: docker compose run --rm --no-TTY bot pytest app/tests/
        language: system
        verbose: true
        pass_filenames: false